language: ruby
sudo: false
cache:
  - bundler
rvm:
- 2.1.5
before_script:
  - rename 's/\.yml.travis$/\.yml/' config/*.yml.travis
  - psql -U postgres -c 'create database travis_ci_test;'
  - RACK_ENV=test bundle exec rake db:schema:load
services:
  - postgresql
addons:
  postgresql: "9.3"
  code_climate:
    repo_token:
      secure: Cc8J0Xm4PMLbZZvdI//NIaKwj9IY5j2RvbpYPrZW8BafbbxdlBZwZsMYnNOCOlSKhZSO87zxTQno3Yyv2ZnzsET1qj3XZ+6W5Q+INmxv9FSMZdbYyO+oRto8X/i0gjO+CerP642AKTOj9omaSxDKLoP/2dr6VKEQaxO4hFWNYgc=
