language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.5
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - printf "test:\n  adapter: postgresql\n  database: travis_ci_test\n  username: postgres\n" > database.yml
  - RACK_ENV=test bundle exec rake db:create db:migrate
services:
  - postgresql
addons:
  postgresql: "9.3"
  repo_token:
    secure: a3KplVoRsWOnQwwTtvsfH0eufR6v8Pro75t5SOf8l7kCp3YkjaU6sfsVsZ9LoFBSlcQEw4M7G/5l7af+Sm8A9Y/OLcze3lunIIZd5TRQM4uvJINwBLxgZo7TTg9/eyzMoxXdLrTfuTd3OweGYAPCFZSfMNDVdjl9wi/7RH420Gg=
