postgres:
  image: postgres:9.5
  environment:
    - "POSTGRES_USER=talkapi"
    - "POSTGRES_PASSWORD=talkapi"
  ports:
    - "5432:5432"

redis:
  image: redis
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"

talkapi:
  dockerfile: Dockerfile
  build: ./
  volumes:
    - ./:/rails_app
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "DATABASE_URL=postgresql://talkapi:talkapi@pg"
    - "REDIS_URL=redis://redis:6379/0"
  # external_links:
  #   - external_postgres_container:pg
  links:
    - postgres:pg
    - redis

sidekiq:
  dockerfile: Dockerfile
  build: ./
  volumes:
    - ./:/rails_app
  command: ["/rails_app/docker/start-sidekiq.sh"]
  environment:
    - "RAILS_ENV=development"
    - "DATABASE_URL=postgresql://talkapi:talkapi@pg"
    - "REDIS_URL=redis://redis:6379/0"
    - "DISABLE_SPRING=true"
    - "SIDEKIQ_VERBOSE=true"
  links:
    - redis:redis
    - postgres:pg