default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV['PG_POOL_SIZE'] || ENV.fetch('RAILS_MAX_THREADS', 8)).to_i %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://talk:talk@localhost') %>

development:
  <<: *default
  database: talk_development

panoptes_development:
  <<: *default
  database: talk_panoptes_development

test:
  <<: *default
  database: talk_test

panoptes_test:
  <<: *default
  database: talk_panoptes_test

staging:
  <<: *default

panoptes_staging:
  <<: *default

production:
  <<: *default

panoptes_production:
  <<: *default
