default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV['PG_POOL_SIZE'] || ENV.fetch('RAILS_MAX_THREADS', 8)).to_i %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://talk:talk@localhost') %>

panoptes_default: &panoptes_default
  <<: *default
  pool: <%= (ENV['PG_POOL_SIZE'] || ENV.fetch('RAILS_MAX_THREADS', 8)).to_i %>
  username: <%= ENV.fetch('PANOPTES_DATABASE_USERNAME', 'talkapi') %>
  password: <%= ENV.fetch('PANOPTES_DATABASE_PASSWORD', 'talkapi') %>
  host: <%= ENV.fetch('PANOPTES_DATABASE_HOST', 'localhost') %>
  url: <%= ENV.fetch('PANOPTES_DATABASE_URL', 'postgresql://talk:talk@localhost') %>

development:
  <<: *default

panoptes_development:
  <<: *panoptes_default
  database: talk_panoptes_development

test:
  <<: *default
  database: talk_test

panoptes_test:
  <<: *panoptes_default
  database: talk_panoptes_test

staging:
  <<: *default

panoptes_staging:
  <<: *panoptes_default

production:
  <<: *default

panoptes_production:
  <<: *panoptes_default
